# docker-compose: https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml
# image: https://hub.docker.com/r/mattermost/mattermost-team-edition

version: '3.8'

services:
  mattermost:
    image: mattermost/mattermost-team-edition:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT}:8065
    volumes:
      - mattermost:/mattermost
    environment:
      - MM_USERNAME=${DB_MYSQL_USER}
      - MM_PASSWORD=${DB_MYSQL_PASSWORD}
      - MM_DBNAME=${DB_MYSQL_NAME}
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - DB_PORT_NUMBER=${DB_MYSQL_PORT}
      # This env is need otherwise, db connection failed
      - MM_SQLSETTINGS_DATASOURCE=${DB_MYSQL_USER}:${DB_MYSQL_PASSWORD}@tcp(mysql:${DB_MYSQL_PORT})/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
    links: 
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: mattermost-mysql
    restart: always
    stdin_open: true
    tty: true
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_config/conf.d:/etc/mysql/conf.d
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  mattermost: